# Generated by Django 4.1.5 on 2023-01-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeepapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Description', models.CharField(max_length=2000)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='BrandSlider',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='OurClientReview',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='heading', max_length=30)),
                ('Message', models.CharField(max_length=2000)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
